name: Singulaire
favicon: null
layout_spectrum: 0.564347030594945
typography_spectrum: 0.46971
title: 'Welcome to Singulaire, a place to discuss the evolution of medical and information technological evolutions'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070302'
    - '#f6f5f3'
    - '#81512b'
    - '#d58256'
    - '#b5a492'
  brandStrength: 0.03241900377906859
  lightness: 0.7614490517880768
  saturation: 0.9178470261394978
  rhythmicContrast: 0.2291439266409725
purpose: []
